Django/Day10/AXF/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('axf.urls', namespace='AXF')),
]

Django/Day10/AXF/axf/urls.py
from django.conf.urls import url

from .views import *
urlpatterns = [
    url(r'^home/', home, name='home'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', market, name='market'),
    url(r'^cart/', cart, name='cart'),
    url(r'^mine/', mine, name='mine'),
    url(r'^login/', login, name='login'),
    url(r'^register/', register, name='register'),
    url(r'^checkuserid/', checkuserid, name='checkuserid'),
    url(r'^logout/', logout, name='logout'),
    url(r'^cartaddto/', cartaddto, name='cartaddto'),
    url(r'^cartadd/', cartadd, name='cartadd'),
    url(r'^cartnumadd/', cartnumadd, name='cartnumadd'),
    url(r'^cartnumreduce/', cartnumreduce, name='cartnumreduce'),
    url(r'^cartdel/', cartdel, name='cartdel'),
    url(r'^cartselect/', cartselect, name='cartselect'),
    url(r'^cartallselect/', cartallselect, name='cartallselect'),
    url(r'^orderadd/', orderadd, name='orderadd'),
    url(r'^order/(\d+)/', order, name='order'),
    url(r'^pay/', pay, name='pay'),
    url(r'^orderunpay/', orderunpay, name='orderunpay'),
    url(r'^ordernopayhandle/', ordernopayhandle, name='ordernopayhandle'),
    url(r'^orderunreceive/', orderunreceive, name='orderunreceive'),
    url(r'^orderconfirm/', orderconfirm, name='orderconfirm'),
]

Django/Day10/AXF/axf/models.py
from django.db import models

# Create your models here.

class Main(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=30)
    trackid = models.CharField(max_length=20)

    class Meta:
        abstract = True #抽象类

#首页-轮播
class MainWheel(Main):
    class Meta:
        db_table = 'axf_wheel'


#首页-导航
class MainNav(Main):
    class Meta:
        db_table = 'axf_nav'


#首页-必须购买
class MainMustbuy(Main):
    class Meta:
        db_table = 'axf_mustbuy'


#首页-购买
class MainShop(Main):
    class Meta:
        db_table = 'axf_shop'


class MainShow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)

    img1 = models.CharField(max_length=100)
    childcid1 =models.CharField(max_length=10)
    productid1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=50)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=10)
    productid2 = models.CharField(max_length=10)
    longname2 = models.CharField(max_length=50)
    price2 = models.CharField(max_length=10)
    marketprice2 = models.CharField(max_length=10)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=10)
    productid3 = models.CharField(max_length=10)
    longname3 = models.CharField(max_length=50)
    price3 = models.CharField(max_length=10)
    marketprice3 = models.CharField(max_length=10)

    class Meta:
        db_table = 'axf_mainshow'



class MainFoodTpye(models.Model):
    typeid = models.CharField(max_length=10)
    typename = models.CharField(max_length=20)
    childtypenames = models.CharField(max_length=150)
    typesort = models.IntegerField()

    class Meta:
        db_table = 'axf_foodtypes'


class Goods(models.Model):
    # 商品id
    productid = models.CharField(max_length=10)
    #商品图片
    productimg = models.CharField(max_length=150)
    #商品名称
    productname = models.CharField(max_length=50)
    #商品长名称
    productlongname = models.CharField(max_length=100)
    #是否精选
    isxf = models.NullBooleanField(default=False)
    #是否买一赠一
    pmdesc = models.CharField(max_length=10)
    #规格
    specifics = models.CharField(max_length=20)
    #价格
    price = models.CharField(max_length=10)
    #超市价格
    marketprice = models.CharField(max_length=10)
    #
    categoryid = models.CharField(max_length=10)
    #子类组id
    childcid = models.CharField(max_length=10)
    #子类组名称
    childcidname = models.CharField(max_length=10)
    #详情页id
    dealerid = models.CharField(max_length=10)
    #库存
    storenums = models.IntegerField()
    #销量
    productnum = models.IntegerField()

    class META:
        db_table = 'axf_goods'

class User(models.Model):
    #用户账号,唯一
    userAccount = models.CharField(max_length=20, unique=True)
    #密码
    userPasswd = models.CharField(max_length=32)
    #昵称
    userName = models.CharField(max_length=20)
    #手机号
    userPhone = models.CharField(max_length=20)
    #地址
    userAdderss = models.CharField(max_length=100)
    #头像路径
    userImg = models.CharField(max_length=150)
    #等级
    userRank = models.IntegerField(default=0)
    #token
    userToken = models.CharField(max_length=50)

    # @classmethod
    # def createuser(cls, account, passwd, name, phone, address, img, rank, token):
    #     u = cls(userAccount=account, userPasswd=passwd, userName=name,
    #     userPhone=phone, userAdderss=address, userImg=img, userRank=rank, userToken=token)
    #     return u


class IsSelect(models.Manager):
    def get_queryset(self):
        return super(IsSelect, self).get_queryset().filter(isDelete=False)

class orderManager(models.Manager):
    def get_queryset(self):
      return super(orderManager, self).get_queryset().filter(isDelete=True)


class Order(models.Model):
    orderid = models.CharField(max_length=32)
    userid = models.CharField(max_length=32)
    money = models.CharField(max_length=32)
    progress = models.IntegerField()

class Cart(models.Model):
    userAccount = models.CharField(max_length=20)
    productid = models.CharField(max_length=10)
    productnum = models.IntegerField()
    productprice = models.CharField(max_length=10)
    isChose = models.BooleanField(default=True)
    productimg = models.CharField(max_length=150)
    productname = models.CharField(max_length=100)
    orderid = models.ForeignKey(Order)
    isDelete = models.BooleanField(default=False)
    objects = IsSelect()
    objects1 = orderManager()

Django/Day10/AXF/axf/forms/login.py
#定制表单类
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=12, min_length=6,
    required=True, error_messages={'required': '用户账号不能为空', 'invalid': '格式错误'},
    widget=forms.TextInput(attrs={'class':'form-control'}))

    passwd = forms.CharField(max_length=16, min_length=6, widget=forms.PasswordInput, required=True, error_messages={'required': '密码不能为空'})

Django/Day10/AXF/axf/views.py
import datetime
import hashlib
import random
import time
import uuid
import os
from django.http import HttpResponse
from django.shortcuts import render, redirect, HttpResponseRedirect

# Create your views here.
from django.urls import reverse
from django.views.decorators.cache import cache_page

from AXF import settings
from axf.models import *
from django.core.cache import cache


def home(request):
    wheel = MainWheel.objects.all()
    nav = MainNav.objects.all()
    mustbuy = MainMustbuy.objects.all()
    shop = MainShop.objects.all()
    shop1 = MainShop.objects.get(id=1)

    mainlist = MainShow.objects.all()
    data = {
        'wheels': wheel,
        'navs': nav,
        'mustbuys': mustbuy,
        'shop1': shop1,
        'shop2': shop[1:3],
        'shop3': shop[3:7],
        'shop4': shop[7:11],
        'main_list': mainlist,
    }
    return render(request, 'axf/home.html', data)


def market(request, categoryid, cid, sortid):
    leftSlider = MainFoodTpye.objects.all()
    if cid == '0':
        productList = Goods.objects.filter(categoryid=categoryid)
    else:

        productList = Goods.objects.filter(categoryid=categoryid, childcid=cid)
    if sortid == '1':
        productList = productList.order_by('-productnum')
    elif sortid == '2':
        productList = productList.order_by('-price')
    elif sortid == '3':
        productList = productList.order_by('price')

    group = leftSlider.get(typeid=categoryid)
    childList = []
    childnames = group.childtypenames
    arr1 = childnames.split('#')
    for str in arr1:
        arr2 = str.split(':')
        obj = {'childName': arr2[0], 'childId': arr2[1]}
        childList.append(obj)

    data = {
        'leftSlider': leftSlider,
        'productList': productList,
        'childList': childList,
        'categoryid': categoryid,
        'cid': cid,

    }
    return render(request, 'axf/market.html', data)


def cart(request):
    token = request.COOKIES.get('token', '')
    user = User.objects.filter(userToken=token)
    if user.exists():
        user = user.first()
        cart = Cart.objects.filter(userAccount=user.userAccount)

        return render(request, 'axf/cart.html', {'user': user,'cart': cart})
    else:
        return HttpResponseRedirect(reverse('AXF:login'))





def mine(request):
    token = request.COOKIES.get('token', '')
    user = User.objects.filter(userToken=token)
    if user.exists():
        user = user.first()

    return render(request, 'axf/mine.html', {'user': user})


from .forms.login import LoginForm


def login(request):
    if request.method == 'POST':
        f = LoginForm(request.POST)
        if f.is_valid():
            name = f.cleaned_data['username']
            pswd = f.cleaned_data['passwd']
            user = User.objects.filter(userAccount=name, userPasswd=my_md5(pswd))
            if user.exists():
                res = HttpResponseRedirect(reverse('AXF:mine'))
                d = datetime.datetime(3000, 1, 2, 3, 4, 5)  # 3000年后失效
                res.set_cookie('token', user.first().userToken, expires=d)
                return res
        else:
            data = {
                'form': f,
                'error': f.errors
            }
            return render(request, 'axf/login.html', data)
    else:
        f = LoginForm()
        return render(request, 'axf/login.html', {'form': f})


def logout(request):
    res = HttpResponseRedirect(reverse('AXF:mine'))
    res.delete_cookie('token')
    return res


def register(request):
    if request.method == 'POST':
        username = request.POST.get('userAccount')
        passwd = request.POST.get('userPasswd')
        email = request.POST.get('userAdderss')
        f = request.FILES['userImg']
        file_name = generate_icon() + os.path.splitext(f.name)[-1]
        filePath = os.path.join(settings.MDEIA_ROOT, file_name)
        with open(filePath, 'wb') as fp:
            for info in f.chunks():
                fp.write(info)
                fp.flush()
        User.objects.create(userAccount=username, userPasswd=my_md5(passwd), userAdderss=email, userImg=file_name,
                            userToken=generate_token())
        return HttpResponseRedirect(reverse('AXF:mine'))
    else:
        return render(request, 'axf/register.html')


from django.http import JsonResponse


# ajax请求,用户名认证
def checkuserid(request):
    userid = request.POST.get('userid')
    try:
        user = User.objects.get(userAccount=userid)
        return JsonResponse({'statu': 'error'})
    except User.DoesNotExist as e:
        return JsonResponse({'statu': 'success'})

# market中添加到购物车
def cartaddto(request):
    token = request.COOKIES.get('token', '')
    num = request.POST.get('num')
    goodid = request.POST.get('goodid')
    good = Goods.objects.get(id=goodid)  # 商品

    try:
        # 查询用户是否登录
        user = User.objects.get(userToken=token)  # 当前用户
        carts = Cart.objects.filter(userAccount=user.userAccount)
        c = None
        # 如果订单不存在就添加订单
        if not carts.exists():

            c = Cart(userAccount=user.userAccount, productid=goodid,
                     productnum=num, productprice=good.price,
                     isChose=True, productimg=good.productimg,
                     productname=good.productlongname, isDelete=False)
            c.save()
            good.storenums -= int(num)
            good.save()
        # 存在订单就加商品数量
        else:
            try:
                # 查询订单是否有该商品
                c = carts.get(productid=goodid)

                c.productnum += int(num)
                # onecart.productprice = '%.2f'%(float(good.price) * onecart.productnum)
                c.save()
                good.storenums -= int(num)
                good.save()
            except Cart.DoesNotExist as e:

                c = Cart(userAccount=user.userAccount, productid=goodid,
                         productnum=num, productprice=good.price,
                         isChose=True, productimg=good.productimg,
                         productname=good.productlongname, isDelete=False)
                c.save()
                good.storenums -= int(num)
                good.save()
        return JsonResponse({'status': 1, 'msg': 'ok'})
    except User.DoesNotExist as e:
        return JsonResponse({'status': 0, 'msg': 'error'})

#market中验证库存
def cartadd(request):
    num = request.POST.get('num')
    goodid = request.POST.get('goodid')
    try:
        good = Goods.objects.get(id=goodid)
        storenums = good.storenums
        if (storenums < int(num)):
            return JsonResponse({'status': 1})
        else:
            return JsonResponse({'status': 2})
    except:
        return JsonResponse({'status': 0})


#增加购物车的商品数
def cartnumadd(request):
    cartid = request.POST.get('cartid')
    try:
        cart = Cart.objects.get(id=cartid)
        cart.productnum += 1
        cart.save()
        num = cart.productnum
        return JsonResponse({'status': 1, 'num': num})
    except:
        pass
#减少购物车的商品数量
def cartnumreduce(request):
    cartid = request.POST.get('cartid')
    token = request.COOKIES.get('token', '')
    try:
        cart = Cart.objects.get(id=cartid)
        user = User.objects.filter(userToken=token)
        if user.exists():
            if(cart.productnum>1):
                cart.productnum -= 1
                cart.save()
            num = cart.productnum
            return JsonResponse({'status': 1, 'num': num})
        else:
            return JsonResponse({'status': 0})
    except:
        return JsonResponse({'msg': 'error'})

# 将购物车的数据删除
def cartdel(request):
    cartid = request.POST.get('cartid')
    token = request.COOKIES.get('token', '')
    try:
        cart = Cart.objects.get(id=cartid)
        user = User.objects.filter(userToken=token)
        if user.exists():
            cart.delete()

            return JsonResponse({'status': 1})
        else:
            return JsonResponse({'status': 0})
    except:
     return JsonResponse({'msg': '订单不存在'})

#ajax请求前端传来cart的id 将数据库中的选择状态数据取反,并传给前端
def cartselect(request):
    cartid = request.POST.get('cartid')
    token = request.COOKIES.get('token', '')
    try:
        cart = Cart.objects.get(id=cartid)
        user = User.objects.filter(userToken=token)
        if user.exists():
            cart.isChose = not cart.isChose
            cart.save()

            return JsonResponse({'status': 1, 'select': cart.isChose})
        else:
            return JsonResponse({'status': 0})
    except:
        return JsonResponse({'msg': '订单不存在'})

#全选ajax请求,
def cartallselect(request):
    if request.method == 'POST':
        token = request.COOKIES.get('token', '')
        try:
            user = User.objects.get(userToken=token)
            carts = Cart.objects.filter(userAccount=user.userAccount)
            flag = 0
            maxcart = carts.count()
            for cart in carts:        #如果购物车所有商品的选择状态都为 True 就将所有的isChose改为false 存入数据库中,否则则全改为true,状态码都为1
                if cart.isChose == True:
                    flag += 1
            if flag == maxcart:
                for cart in carts:
                    cart.isChose = False
                    cart.save()
                return JsonResponse({'status': 1})
            else:
                for cart in carts:
                    cart.isChose = True
                    cart.save()
                return JsonResponse({'status': 1})
        except User.DoesNotExist as e:
            return JsonResponse({'msg': '错是不可能错的'})

#添加订单
def orderadd(request):
    if request.method == 'POST':
        token = request.COOKIES.get('token', '')
        try:
            user = User.objects.get(userToken=token)
            carts = Cart.objects.filter(userAccount=user.userAccount, isChose=True) #状态为已经选择的商品查询出来,并加到订单当中
            if not carts.exists():
                return JsonResponse({'status': -1})
            else:
                oid = generate_icon()
                num = request.POST.get('num')

Django/Day10/AXF/templates/axf/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}
    
    {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base_main.css' %}">
    {% block extcss %}
    
    {% endblock %}

    <script type="text/javascript" charset="utf-8" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'js/base.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'js/md5.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'js/swiper.jquery.js' %}"></script>


    {% block linkscript %}

    {% endblock %}

</head>
<body>
<header>
    {% block header %}

    {% endblock %}
</header>



    {% block base %}

    {% endblock base %}


<footer>

    <a class="home" href="{% url 'AXF:home' %}">
        <dl>
            <dt><span></span></dt>
            <dd>主页</dd>
        </dl>
    </a>
     <a class="market" href="/axf/market/104749/0/0">
        <dl>
            <dt><span></span></dt>
            <dd>闪送超市</dd>
        </dl>
    </a>
     <a class="cart" href="{% url 'AXF:cart' %}">
        <dl>
            <dt><span></span></dt>
            <dd>购物车</dd>
        </dl>
    </a>
     <a class="mine" href="{% url 'AXF:mine' %}">
        <dl>
            <dt><span></span></dt>
            <dd>我的</dd>
        </dl>
    </a>
</footer>


</body>

</html>

Django/Day10/AXF/templates/axf/cart.html
{% extends 'axf/base.html' %}
{% load static %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}

{% block linkscript %}
    <script src="{% static 'app/cart/cart.js' %}"></script>
{% endblock %}

{% block header %}
<div style="margin: auto">购物车</div>
{% endblock %}

{% block Title %}
 购物车
{% endblock %}

{% block base %}

    <div id="cart">


        <div class="full">
            <section>
                <ul>
                    <li>收货人:{{ user.userAccount }}</li>
                    <li>联系方式: 110</li>
                    <li>收货地址: 创客小镇15栋</li>
                </ul>

                <div class="bill">
                    <p>闪送超市</p>
                    <a href="{% url 'AXF:market' 104749 0 0  %}">闪送超市</a>
                    <p>优惠券:满100减99</p>
                </div>


                <menu>
                    <ul>

                            {% for item in cart %}
                                <li class="menuList" id="{{ item.id }}">
                                    <div class="confirm">
                                        <span class="select">
                                            {% if item.isChose %}
                                                <span>√</span>
                                                {% else %}
                                                <span></span>
                                            {% endif %}
                                        </span>
                                    </div>

                                    <a href="#">
                                        <img src="{{ item.productimg }}" alt="">
                                        <p>{{ item.productname }}</p>
                                        <p>¥<span class="price">{{ item.productprice }}</span></p>
                                    </a>

                                    <section>
                                        <button class="reduce">-</button>
                                        <span class="num">{{ item.productnum }}</span>
                                    <button class="add">+</button>
                                    </section>
                                    <button class="delbtn">删除</button>

                                </li>
                            {% endfor %}



                    </ul>


                    <div class="payTheBill">


                        <div class="confirm">
                            <span id="allselect">
                                <span>√</span>
                            </span>
                        </div>

                        <p>全选</p>
                        <p>总价: <span id="totalPrice">0</span></p>
                        <a id="calculate" href="#">结算</a>
                    </div>


                </menu>


            </section>
        </div>
{% endblock base %}

Django/Day10/AXF/templates/axf/home.html
{% extends 'axf/base.html' %}
{% load static %}




{% block extcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/home/home.css' %}">
{% endblock %}



{% block header %}
    <div style="margin: auto">首页</div>
{% endblock %}


{% block linkscript %}
    <script src="{% static 'app/home/home.js' %}"></script>
{% endblock %}


block


{% block Title %}
 首页
{% endblock %}




{% block base %}
{#    盒子#}
<div id="home">
<div class="swiper-container" id="topSwiper">
    <div class="swiper-wrapper">
        {% for wheel in wheels %}
        <div class="swiper-slide">
            <a href=""> <img src="{{ wheel.img }}"  alt=""> </a> </div>
        {% endfor %}
    </div>
<div class="swiper-pagination "></div>
</div>


{#顶层菜单#}
<div class="topMenu">

<nav>
    <ul>
        {% for nav in navs %}
            <li>
                <a href=""><img src="{{ nav.img }}" alt="">
            </a>
            <span>{{ nav.name }}</span>
            </li>
        {% endfor %}

    </ul>
</nav>

</div>

{# 第二个轮播 #}
<div class="swiper-container  " id="swiperMenu">

        <ul class="swiper-wrapper">
            {% for mustbuy in mustbuys %}
                    <li class="swiper-slide">
                        <a href="">
                            <img src="{{ mustbuy.img }}" >
                        </a>
                    </li>
            {% endfor %}

        </ul>
</div>


<div class="CVS">
    <h2><img src="{{ shop1.img }}" alt=""></h2>
    <fieldset>
        {% for shop in shop2 %}
            <a href=""><img src="{{ shop.img }}" alt=""></a>
        {% endfor %}
    </fieldset>
    <ul>
        {% for shop in shop3 %}
            <li><img src="{{ shop.img }}" alt="">
            <span>{{ shop.name }}</span>
            </li>
        {% endfor %}

    </ul>
    <ol>
        {% for shop in shop4 %}
            <li><a href=""><img src="{{ shop.img }}" alt=""></a></li>
        {% endfor %}
        
    </ol>
</div>

<div class="mainInfo">


    {% for main in main_list %}
     <section>
            <h3>{{ main.name }}
                <a href="">更多></a>
                <span></span>
            </h3>
            <div>
                <a href=""><img src="{{ main.img }}" alt=""></a>
            </div>
            <ul>
                <li>
                    <a href="">
                        <img src="{{ main.img1 }}" alt="">
                        <p class="description">{{ main.longname1 }}</p>
                        <span>¥{{ main.price1 }}</span>
                        <s>¥{{ main.marketprice1 }}</s>
                    </a>
                    <button><span>&#43;</span></button>
                </li>
                <li>
                    <a href="">
                        <img src="{{ main.img2 }}" alt="">
                        <p class="description">{{ main.longname2 }}</p>
                        <span>¥{{ main.price2 }}</span>
                        <s>¥{{ main.marketprice2 }}</s>
                    </a>
                    <button><span>&#43;</span></button>
                </li>
                <li>
                    <a href="">
                        <img src="{{ main.img3 }}" alt="">
                        <p class="description">{{ main.longname3 }}</p>
                        <span>¥{{ main.price3 }}</span>
                        <s>¥{{ main.marketprice3 }}</s>
                    </a>
                    <button><span>&#43;</span></button>
                </li>
            </ul>

     
        </section>
    {% endfor %}
        </div>


</div>




{% endblock base %}

Django/Day10/AXF/templates/axf/market.html
{% extends 'axf/base.html' %}
{% load static %}

{% block linkscript %}
    <script src="{% static 'app/market/market.js' %}"></script>
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}



{% block header %}
    <div style="margin: auto">闪购

    </div>
{% endblock %}


{% block Title %}
 闪购
{% endblock %}

{% block base %}

<div id="market">
{#左边商品类型#}
<aside>

        <ul>
            {% for foo in leftSlider %}


              <li>
                  <a href="{% url 'AXF:market' foo.typeid 0 0%}">{{ foo.typename }}</a>

                  {% if categoryid == foo.typeid %}

              <div class="yellowSlide"></div>
                  {% endif %}
              </li>

            {% endfor %}


        </ul>

</aside>


{#类型#}
<section>
     <nav>
                <ul>
                    <li id="all_type">
                        <span>
                            全部类型
                            <span id="all_type_icon" class="glyphicon glyphicon-chevron-down"></span>
                        </span>
                    </li>
                    <li id="sort_rule">
                        <span>
                            综合排序
                            <span id="sort_rule_icon" class="glyphicon glyphicon-chevron-down"></span>
                        </span>
                    </li>
                </ul>
            </nav>



    <menu>
        <ul>
            {% for item in productList %}
                <li>
                    <a href="#">
                        <img src="{{ item.productimg }}" alt="">
                            <div class="shoppingInfo">
                                <h6>{{item.productlongname }}</h6>
                                <div class="detailTag">
                                    <span>精选</span>

                                </div>
                                <div class="unit">{{ item.specifics }}</div>
                                <div class="price">
                                    <span>¥{{ item.price }}</span>
                                <s>¥{{ item.marketprice|floatformat  }}</s>
                                </div>
                            </div>
                    </a>
                <section>
                    <button  class="reduce">-</button>
                    <span class="num">0</span>
                    <button  class="add">+</button>
                </section>
                    <button goodid="{{ item.id }}" class="addtocart">加入购物车</button>

                </li>
            {% endfor %}

        </ul>

{#         全部类型#}
                <div id="typeid">
                    <div>
                          {% for child in childList %}
                              <a href="{% url 'AXF:market' categoryid child.childId 0 %}"><span>{{ child.childName }}</span>  </a>
                          {% endfor %}
                    </div>
                </div>



                    <div id="sortdiv">
                        <div>
                       <a href="{% url 'AXF:market' categoryid cid 0 %}" class="sorta">
                            <span>综合排序</span>
                        </a>
                        <a href="{% url 'AXF:market' categoryid cid 1 %}" class="sorta">
                            <span>销量排序</span>
                        </a>
                        <a href="{% url 'AXF:market' categoryid cid 2 %}" class="sorta">
                            <span>价格降序</span>
                        </a>
                        <a href="{% url 'AXF:market' categoryid cid 3 %}" class="sorta">
                            <span>价格升序</span>
                        </a>
                        </div>
                    </div>

    </menu>




</section>


</div>

{% endblock base %}

Django/Day10/AXF/templates/axf/register.html
{% extends 'axf/base.html' %}
{% load static %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'app/register/register.css' %}">
{% endblock %}

{% block linkscript %}
    <script src="{% static 'app/register/register.js' %}"></script>
{% endblock %}

{% block Title %}
    注册
{% endblock %}


{% block header %}
    <div style="margin: auto">注册</div>
{% endblock %}



{% block base %}
<div id="register">
            <div id="header">
                <a href="{% url 'AXF:mine' %}"> <p>返回</p> </a>
            </div>
    <form action="{% url 'AXF:register' %}" class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group">
            <span class="input-group-addon">账号</span>
            <input type="text" name="userAccount"    class="form-control"
              aria-describedby="basic-addon1"     id="account" placeholder="账号长度为6到18个字符">

        </div>
            <p id="msg"></p>


        <div class="input-group">
            <span class="input-group-addon">密码</span>
            <input id="pass" type="password" name="userPass"
              aria-describedby="basic-addon1"  class="form-control"  placeholder="密码长度至少为8个字符">
        </div>
                        <p id="passwdmsg"></p>                 <br>

        <div class="input-group">
            <span class="input-group-addon">验证</span>
            <input type="password" name="userPasswd" id="passwd"
              aria-describedby="basic-addon1"  class="form-control"  placeholder="密码长度为8个字符">
        </div>
         <p id="pswdmsg"></p> <br>



        <div class="input-group">
            <span class="input-group-addon">邮箱</span>
            <input name="userAdderss" id='email' type="text" required="required" class="form-control" aria-describedby="basic-addon1">
        </div>
        <p id="emailmsg"></p>
        <br>
        <div class="input-group">
            <span class="input-group-addon">头像</span>
            <input name="userImg" type="file" required="required" class="form-control" aria-describedby="basic-addon1">
        </div>
        <br>

        <div class="input-group">
            <span class="input-group-addon">注册</span>
            <input value="注册" type="submit" id="registerid" required="required" class="form-control" aria-describedby="basic-addon1">
        </div>
        <br>

    </form>
</div>
{% endblock %}