Django/Day04/bootstarp page/Day03Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('book.urls',namespace='book')),
    url(r'^author/', include('author.urls', namespace='author')),
    url(r'^publisher/', include('publisher.urls', namespace='publisher')),

]

Django/Day04/bootstarp page/author/urls.py
from django.conf.urls import url

from author.views import *

urlpatterns = [
    url(r'^index/', index, name='index'),

    # url(r'^detail/', detail, name='detail'),
    url(r'^detail/(\d+)/', detail, name='detail'),
    url(r'^page/(\d+)/', page, name='page'),
    url(r'^page', page1)
]

Django/Day04/bootstarp page/book/urls.py
from django.conf.urls import url

from book.views import *

urlpatterns = [
    url(r'^index/', index,name='index'),
    url(r'^list/', list, name='list'),
    url(r'^detail/(\d+)/', detail, name='detail'),
]

Django/Day04/bootstarp page/publisher/urls.py
from django.conf.urls import url

from publisher.views import *

urlpatterns = [
    url(r'^index/', index,name='index'),
    url(r'^detail/(\d+)/',  detail, name='detail'),
]

Django/Day04/bootstarp page/author/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    gender = models.BooleanField(default=True)

    def __str__(self):
        return self.first_name + self.last_name

Django/Day04/bootstarp page/book/models.py
from django.db import models

# Create your models here.
from author.models import Author
from publisher.models import Publisher

class Book(models.Model):
    title = models.CharField(max_length=100,verbose_name='书名',null=True,blank=True)
    author = models.ForeignKey(Author)
    publishers = models.ManyToManyField(Publisher)
    publish_date = models.DateField()

    def __str__(self):
        return self.title

Django/Day04/bootstarp page/publisher/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=30)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=20)
    website = models.URLField()

    def __str__(self):
        return self.name

Django/Day04/bootstarp page/author/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
import math
def index(request):
    authors = Author.objects.all()
    return render(request, 'author/index.html', {'authors':authors})



def detail(request,author_id):
    author = Author.objects.get(id=author_id)
    return render(request,'author/detail.html',{'author':author})


def page1(request):
    return page(request, 1)

#分页
def page(request,page):
    per_num = 3 #每页数量
    start = (int(page) - 1) * per_num
    end = start + per_num
    authors = Author.objects.all()
    #总页数
    pages = math.ceil(authors.count() / per_num)
    page_list = [i+1 for i in range(pages)]
    page_next = int(page) + 1 #上一页

    page_prev = int(page) - 1  #
    if page_prev == 0:
        page_prev = 1
    if page_next == pages + 1:
        page_next = pages
    page2 = int(page)
    if page2 == pages+1:
        page2 = 1



    return render(request,'author/page.html',{'authors':authors[start:end], 'pages_list':page_list, 'page_prev':page_prev, 'page_next':page_next,'page2':page2})

Django/Day04/bootstarp page/book/views.py
from django.shortcuts import render
from .models import Book
# Create your views here.

def index(request):
    return render(request,'book/index.html')

def list(request):
    books = Book.objects.all()
    return render(request, 'book/list.html', {'books':books})

def detail(request, bookid):

    book = Book.objects.get(id=bookid)
    return render(request, 'book/detail.html', {'book':book})

Django/Day04/bootstarp page/publisher/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def index(request):
    return render(request,'publisher/index.html')

def detail(request,publisher_id):
    publisher = Publisher.objects.get(id=publisher_id)
    return render(request, 'publisher/detail.html',{'publisher':publisher})

Django/Day04/bootstarp page/book/templates/book/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
            <h3>书籍详情</h3>
                <p>{{ book.title }}</p>
                <p>
                    <a href="{% url 'author:detail' book.author.id %}">
                    {{ book.author }}
                   </a>
                </p>
                {% for publisher in book.publishers.all %}
                    <a href="{% url 'publisher:detail' publisher.id %}">{{ publisher }}</a>
                    {% if not forloop.last %}
                        | 哈哈，你被我控制了
                    {% endif %}
                {% endfor %}

</body>
</html>

Django/Day04/bootstarp page/book/templates/book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'book:list' %}">点击跳转到所有书籍 </a>
</body>
</html>

Django/Day04/bootstarp page/book/templates/book/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for book in books %}
            <li>

                <a href="{% url 'book:detail' book.id %}"> {{ book.title }}  </a>
            </li>
        {% endfor %}

    </ul>
</body>
</html>