Django/Day03/Day03Django/Day03Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('book.urls',namespace='book')),
    url(r'^author/', include('author.urls', namespace='author')),
    url(r'^publisher/', include('publisher.urls', namespace='publisher')),

]

Django/Day03/Day03Django/author/urls.py
from django.conf.urls import url

from author.views import *

urlpatterns = [
    url(r'^index/', index, name='index'),

    # url(r'^detail/', detail, name='detail'),
    url(r'^detail/(\d+)/', detail, name='detail'),
]

Django/Day03/Day03Django/book/urls.py
from django.conf.urls import url

from book.views import *

urlpatterns = [
    url(r'^index/', index,name='index'),
    url(r'^list/', list, name='list'),
    url(r'^detail/(\d+)/', detail, name='detail'),
]

Django/Day03/Day03Django/publisher/urls.py
from django.conf.urls import url

from publisher.views import *

urlpatterns = [
    url(r'^index/', index,name='index'),
    url(r'^detail/(\d+)/',  detail, name='detail'),
]

Django/Day03/Day03Django/author/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    gender = models.BooleanField(default=True)

    def __str__(self):
        return self.first_name + self.last_name

Django/Day03/Day03Django/book/models.py
from django.db import models

# Create your models here.
from author.models import Author
from publisher.models import Publisher

class Book(models.Model):
    title = models.CharField(max_length=100,verbose_name='书名',null=True,blank=True)
    author = models.ForeignKey(Author)
    publishers = models.ManyToManyField(Publisher)
    publish_date = models.DateField()

    def __str__(self):
        return self.title

Django/Day03/Day03Django/publisher/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=30)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=20)
    website = models.URLField()

    def __str__(self):
        return self.name

Django/Day03/Day03Django/author/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def index(request):
    authors = Author.objects.all()
    return render(request, 'author/index.html', {'authors':authors})



def detail(request,author_id):
    author = Author.objects.get(id=author_id)
    return render(request,'author/detail.html',{'author':author})

Django/Day03/Day03Django/book/views.py
from django.shortcuts import render
from .models import Book
# Create your views here.

def index(request):
    return render(request,'book/index.html')

def list(request):
    books = Book.objects.all()
    return render(request, 'book/list.html', {'books':books})

def detail(request, bookid):

    book = Book.objects.get(id=bookid)
    return render(request, 'book/detail.html', {'book':book})

Django/Day03/Day03Django/publisher/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def index(request):
    return render(request,'publisher/index.html')

def detail(request,publisher_id):
    publisher = Publisher.objects.get(id=publisher_id)
    return render(request, 'publisher/detail.html',{'publisher':publisher})

Django/Day03/Day03Django/author/templates/author/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h3>作者</h3>
    <p>作者的姓名{{ author }}</p>
    <p>作者的email：{{ author.email }}</p>
    <p>作者的性别:
        {% if author.gender %}
                  男
            {% else %}
            女
        {% endif %}
    </p>

</body>
</html>

Django/Day03/Day03Django/author/templates/author/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>哈哈,你已经被我控制了</div>
<ul>
{% for author in authors %}
        <li><a href="{% url 'author:detail' author.id %}">{{ author }}</a></li>
{% endfor %}
</ul>

</body>
</html>

Django/Day03/Day03Django/publisher/templates/publisher/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>出版社详情</h3>
<p>出版社名称:{{ publisher.name }}</p>
<p>出版社国家:{{ publisher.country }}</p>
<p>出版社城市：{{ publisher.city }}</p>
<p>出版社地址：{{ publisher.address }}</p>

</body>
</html>

Django/Day03/Day03Django/publisher/templates/publisher/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'book:index' %}">点击跳转到book</a>
</body>
</html>